spring:
  application:
    name: airBnbApp

# DB Configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# API path
server:
  servlet:
    context-path: /api/v1

# JWT SecretKey
jwt:
  secretKey: kfjhvb3i87oiawuwor2aui4ytop8237v5i8ay927b83q237862459r8yvuiwcbwyhUXDETY2OU37IWUTI

frontend:
  url: http://localhost:8080

# Stripe configuration
stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}

  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET_KEY}
