spring:
  application:
    name: airBnbApp

# DB Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/airBnbDB
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# API path
server:
  servlet:
    context-path: /api/v1
